name: New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout sources
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v4
    - name: Setup Java 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
    - run: echo "JAVA_18=$JAVA_HOME" >> $GITHUB_ENV
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create DMG
      run: ./gradlew packageDistributionForCurrentOS --info
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ADBugger-dmg
        path: build/output/main/dmg/ADBugger-${{ github.event.inputs.version }}.dmg

