name: Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest  # Specifies that the job runs on a macOS runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout sources
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4  # Uses the setup-java action to set up JDK 18
        with:
          java-version: 17  # Specifies the version of Java to set up
          distribution: 'temurin'  # Specifies the distribution of Java to set up (e.g., adopt, zulu, temurin)

      - run: echo "JAVA_18=$JAVA_HOME" >> $GITHUB_ENV  # Sets the JAVA_HOME environment variable
      
      - run: /usr/libexec/java_home -V




        


